execution_engine: asyncio

logger:
  transports: [console]
  level: info

mcp:
  servers:
    arxiv:
      transport: sse
      url: "http://127.0.0.1:8060/sse"

llm:
  provider: openai
  openai:
    api_key: ""

    base_url: "http://127.0.0.1:11434/v1"

    model: "qwen2.5:14b-instruct"